### ISSUE TITLE
race condition in chapter 5's registered TODO server

### ISSUE THREAD

**Issue by nhooyr** [sasa1977/elixir-in-action#11]
https://github.com/sasa1977/elixir-in-action/blob/c6c0813b1e463fe1211a0a5d998b3528752bb7b4/code_samples/ch05/registered_todo_server.ex#L4

If a client calls one of the interface functions after starting the server, but the server has not registered its alias, the client will get an error.

**Comment by sasa1977** [comment]
This is indeed a race condition, well spotted! 

The solution is to have a synchronous start, where the spawned process sends the confirmation message back to the caller, and the caller awaits for this message before proceeding further. This way, the caller can resume only after the server has been fully started and registered.

Normally you don't need to write such code yourself. In real-world you'll never need to use `spawn` yourself. Instead, you'll rely on higher-level abstractions such as `GenServer`, which is treated in chapters 6 and 7. `GenServer` implements synchronous starting, thus ensuring that the caller is blocked until the server is fully initialized.

I'll consider adding this remark to the chapter 5 in the next edition.

Thanks for reporting!

**Comment by 0rzech** [comment]
Wouldn't calling `Process.register/2` outside lambda help in this particular case too? I did it like so:

```elixir
def start(entries \\ []) do
  spawn(fn -> loop(TodoList.new(entries)) end)
  |> Process.register(:todo_server)
end
```

(source code is [here](https://orzechowski.tech/git/orzech/elixir-in-action/src/branch/master/registered_todo_server.ex)) and calling `TodoList.CsvImporter.import!("todo.csv") |> TodoList.entries() |> TodoServer.start(); TodoServer.entries()` in iex runs fine instead of failing with:

```
** (ArgumentError) argument error
    :erlang.send(:todo_server, {:entries, #PID<0.96.0>})
    registered_todo_server.ex:23: TodoServer.entries/0
```

**Comment by 0rzech** [comment]
Wouldn't calling `Process.register/2` outside lambda help in this particular case too? I did it like so:

```elixir
def start(entries \\ []) do
  spawn(fn -> loop(TodoList.new(entries)) end)
  |> Process.register(:todo_server)
end
```

(source code is [here](https://orzechowski.tech/git/orzech/elixir-in-action/src/branch/master/registered_todo_server.ex)) and calling `TodoList.CsvImporter.import!("todo.csv") |> TodoList.entries() |> TodoServer.start(); TodoServer.entries()` in iex runs fine instead of failing with:

```
** (ArgumentError) argument error
    :erlang.send(:todo_server, {:entries, #PID<0.96.0>})
    registered_todo_server.ex:23: TodoServer.entries/0
```

**Comment by sasa1977** [comment]
Registering in the starter process would indeed work here. However, this is typically not done because it can lead to some strange race conditions. 

As you'll see in the later chapters, with most process abstractions, such as GenServer and Supervisor, the new process registers itself. The reason why that approach works correctly is because these abstractions offer synchronous start, while simple spawn is asynchronous. For example, when you invoke `GenServer.start_link` (which under the hood performs a spawn), the function returns only after the process has been started, initialized its state, and successfully registered its alias.

**Comment by 0rzech** [comment]
Thank you for detailed explanation.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
