### ISSUE TITLE
unnecessary setting in the ets example

### ISSUE THREAD

**Issue by nhooyr** [sasa1977/elixir-in-action#14]
https://github.com/sasa1977/elixir-in-action/blob/c6c0813b1e463fe1211a0a5d998b3528752bb7b4/code_samples/ch10/profile_cache/lib/ets_page_cache.ex#L21

`:protected` is not necessary because it is the default. Also, the book says in chapter 10:

> Finally, you opt for protected access because you’ll synchronize cache writes in the cache process. This means only **client** process must be able to write to the table, but all processes must have read access.

Shouldn't it go, 

> This means only the **cache** process must be able to write to the table, but all processes out have read access?

**Comment by sasa1977** [comment]
> :protected is not necessary because it is the default.

It is not necessary, but I wanted to be explicit about the access to make it clear that `:protected` is intentional, rather than accidental.

Regarding your second point, it should indeed be the __cache__ process. This is already mentioned in [the errata](https://manning-content.s3.amazonaws.com/download/2/bc9b4e2-d489-424f-afe5-6206861729ee/juric_exlixirinaction_err_7.html).
